### ISSUE TITLE
English grammar issue for a sentence 

### ISSUE THREAD

**Issue by ybdesire** [hax/hax.github.com#30]
I've learned a lot from your slide "js-the-best". https://github.com/hax/hax.github.com/blob/master/2015/js-the-best/hujiang.md.

And I think the sentence "Language features is Important for productivity" at the "hujiang.md" should be modified to 
"Language feature is Important for productivity" 
or 
"Language features are Important for productivity". 

Do you think so?

**Comment by zpbx** [comment]
Guess you are right. :+1:

**Comment by hax** [comment]
Thank you, I'll fix it soon.
